projects:
  Maxi80 Artwork API:
    schemaPath: Maxi80/src/main/graphql/schema.json
    includes:
      - Maxi80/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: errgnkbey5cntllyevjxpwxy7e
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: Maxi80/src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: eu-west-1
      endpoints:
        prod: >-
          https://mgtbxnog4jgwjboj7b5lro73ly.appsync-api.eu-west-1.amazonaws.com/graphql
